### ISSUE TITLE
Problem running QC_stats_Final.py on Biowulf

### ISSUE THREAD

**Issue by seandavi** [NCI-CCR-GB/ClinomicsScripts#1]
Sivasish might have fixed this, but it seems the python version problem:

```
$ which python
/usr/local/Anaconda/envs/py3.4.3/bin/python

$ python /data/Clinomics/Tools/QC_stats_Final.py SUBJECT/HD753/CL0015_T_P/ucsc.hg19.bwamem/bam/CL0015_T_P.final.bam > test
File "/data/Clinomics/Tools/QC_stats_Final.py", line 76
if (depth >= 1000):
```

**Comment by sentisci** [comment]
can a valid output file/s and readme for script be included. ?

**Comment by seandavi** [comment]
Who originally wrote the script?

**Comment by seandavi** [comment]
Hi, @sentisci. We hope to be able to make these scripts more usable over time, but for the time being, we haven't spent much time on documentation or testing.

**Comment by seandavi** [comment]
Who was the original author, @sentisci?

**Comment by sentisci** [comment]
Script is from Manoj .

**Comment by zhujack** [comment]
Script location: /data/Clinomics/Tools/

**QC Script:** QC_stats_Final.py
Panel Example: python QC_stats_Final.py **CL0015_T_P.final.bam** /data/Clinomics/Ref/serpentine_resources/design/Agilent_SureSelect_Killian_Version4.target.hg19.merged.bed > outputfile
Exome Example: python QC_stats_Final.py **CL0012_T_E.final.bam** /data/Clinomics/Ref/serpentine_resources/design/Agilent_SureSelect_Clinical_Research_Exome.design.hg19.merged.bed > outputfile

Note: Please change line #31, 32, 151, & 156 accordingly to include it in Snakemake rules.

**Failed Exon list Script:** failed_Exon_Final.pl
Example: perl failed_Exon_Final.pl <.../SUBJECT/HD753/CL0015_T_P/ucsc.hg19.bwamem/qc/**CL0015_T_P.final.bam.depth_per_base**> THRES

For Panel Tumor: THRES is 50
For Panel Normal: THRES is 20

**Comment by seandavi** [comment]
So, I looked at the script.  It is written to conform to python 2, not python 3.  Jack, you'll need to 

```
module load python/2.7.9
```

for this script to work.  I checked and after doing so, this appears to work.  I opened issue #2 to address the hard-coded paths.
